parent: AngarTheme
name: child_AngarTheme
display_name: Child theme of AngarTheme's theme
version: 1.0.1
assets:
  use_parent_assets: true
  css:
    all:
      - id: bxslider
        path: assets/css/libs/jquery.bxslider.css
      - id: font-awesome
        path: assets/css/font-awesome.css
      - id: angartheme
        path: assets/css/angartheme.css
      - id: homemodyficators
        path: assets/css/home_modyficators.css
      - id: black
        path: assets/css/black.css
      - id: custom
        path: assets/css/custom.css
      - id: RWD
        path: assets/css/rwd.css

  js:
    all:
      - id: bxslider
        path: assets/js/libs/jquery.bxslider.min.js
      - id: angartheme
        path: assets/js/angartheme.js
      - id: achild_angar
        path: assets/js/custom.js

global_settings:
    hooks:
      modules_to_hook:
      displayNav1:
        - angarcontact
      displayNav2:
        - ps_languageselector
        - ps_currencyselector
	- NDCVatDisplay
      displayTop:
        - ps_shoppingcart
        - ps_searchbar
	- ps_customersignin


 

